version: '2'
services:
    studentjobs-app:
        image: studentjobs
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://studentjobs-mysql:3306/studentjobs?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    studentjobs-mysql:
        extends:
            file: mysql.yml
            service: studentjobs-mysql
